/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class AppTest extends Specification {
    def "application can be constructed..."() {
        setup:
        def app = new App()

        when:
        2+2

        then:
        app != null
    }
}
