version: "2"
services:
  pony-server:
    build:
      context: pony-server

  python-worker:
    build:
      context: python-worker
    links:
      - pony-server

  go-worker:
    build:
      context: go-worker
    links:
      - pony-server

  groovy-worker:
    build:
      context: groovy-worker
    links:
      - pony-server

  tcl-worker:
    build:
      context: tcl-worker
    links:
      - pony-server

  # elixir-worker:
  #   build:
  #     context: elixir-worker
  #   links:
  #     - pony-server