version: "2"
services:
  pony-server:
    build:
      context: pony-server

  python-worker:
    build:
      context: python-worker

  go-worker:
    build:
      context: go-worker

  groovy-worker:
    build:
      context: groovy-worker
